### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Blatts12** [Firew0lf/exppipes#1]
https://paste.dimdev.org/esebogakal.mccrash

setup:

https://imgur.com/XCKvJUD

**Comment by Ihamfp** [comment]
This GUI has been acting weirdly since the beginning, I'll change it one day...

**Comment by Ihamfp** [comment]
The fixed build has been uploaded to [Curse](https://minecraft.curseforge.com/projects/exponentialistics-pipes/files/2698662)
