### ISSUE TITLE
Game Freeze When Requesting More Items Than Are in System With Crafting Recipe

### ISSUE THREAD

**Issue by voidsong-dragonfly** [Firew0lf/exppipes#10]
When I tried to request more items than were present in the system through the table, and there was a crafting recipe for those items, the game froze and would no respond. Log below
https://pastebin.com/CwGuDtcn

**Comment by Ihamfp** [comment]
I managed to get a crash in the GUI (will push the fix along with some features when they're done), but I doubt it's related to your freeze. Could you provide a link to your world/modpack if any, and a list of steps to get the freeze ? I also see some connection/routing errors in your log, I'll try to fix them.

**Comment by voidsong-dragonfly** [comment]
Hmm, I tried it again and it worked fine this time. Dunno, may have been something else that just happened to coincide with that. Sorry about that.
