### ISSUE TITLE
[FR] Ability to Type in Number to Request/LargerButtons

### ISSUE THREAD

**Issue by voidsong-dragonfly** [Firew0lf/exppipes#11]
When requesting items from the table or request pipe, to get to 64 items I must click 64 times. This gets boring rather quickly. Could you either add a typing field for it or make, say 16x buttons? That would make requesting stacks much easier.

**Comment by Ihamfp** [comment]
You can use the mouse wheel to select the number of items, but yeah I will add modifiers with shift/ctrl to request more items, or maybe more buttons.

**Comment by Ihamfp** [comment]
Uploading a build with the new count selection system right now. Basically, Shift multiplies the +/- count by 64, and Ctrl by 16. Also works with the mouse wheel !
