### ISSUE TITLE
Pipe opaqueness

### ISSUE THREAD

**Issue by Paril** [Firew0lf/exppipes#15]
A way of applying (and thusly removing) opaqueness on a pipe.

Originally I thought waterproofing (perhaps the default pipes could be washed away by water, since they're "open", but adding waterproofing makes them invincible to water and makes them opaque as well), but I think coloring the pipes would make more sense. Right-clicking a pipe with a dye will fill the transparent area of the pipe with the color of the dye, and make it opaque (not show items flowing through it). Shift-rightclicking the pipe will remove the dye rather than changing connection (or if there's a deadzone where shift-rightclicking does nothing, maybe that can be the removal position). Would allow - obviously - colored pipes to differentiate networks (and since you already have shift-rightclick for connection changing, you don't need color separation or any other similar code changes, it'd only be for visual identification), which is also a big bonus, and doesn't need any new items or mechanics.

**Comment by Ihamfp** [comment]
Not quite opaque, but colored at least :p.
