### ISSUE TITLE
1.14.4 Support

### ISSUE THREAD

**Issue by Paril** [Firew0lf/exppipes#17]
1.14.4 seems to be gaining traction; might be a good time to get this working on 1.14.4. It'd be one of the first/only pipe mods for it as of yet.

So far, Tubes Reloaded seems to be the only similar mod, and it's nowhere near as feature-complete as exppipes is.

**Comment by Ihamfp** [comment]
Forge for 1.14 is still in pre-release, and 1.14 changed a **lot** of things in modding, lags a lot more, and has none of the mods exppipes depends on.

I may drop a 1.14 release, but it will be mostly unsupported and with less features.

EDIT: [reminder to myself](https://gist.github.com/williewillus/353c872bcf1a6ace9921189f6100d09a)

**Comment by BrewingCoder** [comment]
Skip 1.15, close this and open a ticket to 15.2 which is where most of the mods are releasing to. It seems the be the next long term version over any of the 14.x

**Comment by Ihamfp** [comment]
I haven't touched the code in months, mostly because of a lack of time... Also there are still some bugs I can't fix. Might look into porting the code to Fabric as well. If anyone wants access to the repo, just ask.

**Comment by Ihamfp** [comment]
Next target is 1.15.2, 1.14 will most likely not be supported.
