### ISSUE TITLE
Connection breaks don't re-enable until a block update occurs

### ISSUE THREAD

**Issue by Paril** [Firew0lf/exppipes#18]
Shift-rightclicking a connection to remove it immediately shows the removal, but trying to add it back requires a block update for it to visually update.

**Comment by Ihamfp** [comment]
Known bug, I'll take a look eventually...

**Comment by Paril** [comment]
Sounds good! Also you mentioned in the original thread about output pipes not supporting the connections despite visually updating, hopefully we can get that fixed too

**Comment by Ihamfp** [comment]
Fixed in the next commit. I'm working on the opaque pipes thing now :D

EDIT: ok it just got much worse, now the connection updates are sent to the client but only after three clicks (and the opacity/color update after two...). Will not push today...
