### ISSUE TITLE
NPE updating screen

### ISSUE THREAD

**Issue by MasterEnderman** [Firew0lf/exppipes#19]
Exponentialistics Pipes: 0.2.7a
Forge: 14.23.5.2838
Crash-Report: https://paste.dimdev.org/ayidujajah.mccrash

**Comment by Ihamfp** [comment]
What are the steps needed to reproduce the crash ?
It looks easy to fix, but I also wanna check it's really fixed :p I guess clicking somewhere in the request station gui ?

(also I may take some take to push a new version, as I don't have my main computer with me atm)

**Comment by MasterEnderman** [comment]
requesting 1 item via the request station gui

**Comment by Ihamfp** [comment]
I *finally* got enough time to setup everything on my laptop, sorry if I take too long.
Should be fixed in next version.
