### ISSUE TITLE
Extraction?

### ISSUE THREAD

**Issue by BrewingCoder** [Firew0lf/exppipes#2]
How do you extract items into the network?

I've put routed pipes with sink filters on machines (ore processing, etc)

I've got providers on inventory for final product storage

but I can't figure out how to get items out of the chest/inventory where inbound raw materials get dumped.

**Comment by Ihamfp** [comment]
You put providers on the chests containing the materials needed for the craft, and supplier/crafting pipes on machines to automatically request the items.

**Comment by Ihamfp** [comment]
Just updated the wiki a bit, feel free to ask if you have more questions.

Edit: there's now way to *just* extract items from an inventory into the network, because that's exactly what hoppers do :p .

**Comment by BrewingCoder** [comment]
Hoppers are slow man. :/

If you really would like to be the successor to LP, which btw was one of my favorite mods, you would want a pipe that would extract into the network at more than 1 item per 8 ticks.

**Comment by Ihamfp** [comment]
I'll add it on next update, with a configurable extraction rate.

**Comment by Ihamfp** [comment]
Uploading the build right now

**Comment by BrewingCoder** [comment]
Dude, You rock! Will put it on my server ASAP!
