### ISSUE TITLE
Stock Keeper Pipe looks only to the first inventory slot

### ISSUE THREAD

**Issue by andrew-diamondj** [Firew0lf/exppipes#24]
MC 1.12.2
Forge 14.23.5.2854
exppipes-0.2.8.jar

[Make following setup](https://imgur.com/a/neR6koa)
- Set Provider Pipe to provide wood planks and put some planks to the right chest
- Set Stock Keeper Pipe to keep [3 planks](https://imgur.com/a/h4pqxE9) in the left chest.

Wood planks will start moving to the left chest [until 3 ones](https://imgur.com/a/EyeTvPH) gets there to the first slot. If you put some more wood to the first slot, unnecessary items will go back to the provider, and 3 ones are again in the chest. But if you put some planks to the [second inv. slot of the chest](https://imgur.com/a/H4t9fRQ), or some other slot, the Stock Keeper Pipe will ignore it. You can again change items count of the first slot, and again it will be  fetched to 3, ignoring other slots.

**Comment by Ihamfp** [comment]
Can't fix it today, I'll take a look at it tomorrow... And I can't even recall how I coded this pipe's behavior x)

**Comment by andrew-diamondj** [comment]
OK, no problem )

**Comment by Ihamfp** [comment]
Turns out the stock keeper pipe was programmed in such a way that each filter only watches the one corresponding slot. This might have been fine when I added it, but now with the fuzzier filters it doesn't work quite well. Also it turns out you can set >64 items filters in the pipe config, but the game will quickly detect it as invalid and remove the filter...

**Comment by andrew-diamondj** [comment]
Yeah, having control over slot number can be useful if stock keeper is connected with some kind of furnaces for example that have separate slot for fuel and smelting items, and both are given from a same side. 
By the way, it would be great to have some description for pipes ))

**Comment by Ihamfp** [comment]
Exact slot control is complicated to implement, so I went for a system that scans the whole container, determines if items should be added or removed (removing excess items immediately), and requests missing items. Filters overlaps might still be a problem, but in a different way.
