### ISSUE TITLE
Crash on Retriever Pipe

### ISSUE THREAD

**Issue by andrew-diamondj** [Firew0lf/exppipes#25]
MC 1.12.2
Forge 14.23.5.2854
exppipes-0.2.8.jar

Create new world, put a chest, put a Retriever Pipe, connected to a chest. Game crashes.
[logs](https://pastebin.com/nZ3igVUu)

**Comment by Ihamfp** [comment]
Fixed in next commit. I don't think this pipe was meant to be public... Well, it is now x) .
