### ISSUE TITLE
Crash on server on start

### ISSUE THREAD

**Issue by andrew-diamondj** [Firew0lf/exppipes#26]
Server: Mohist version: 1.12.2-1.12.2-a99a910
exppipes version: 0.2.8

No other mods used.
Just started server, no world had been created yet.

[logs](https://pastebin.com/uKGBEEWU)

**Comment by Ihamfp** [comment]
Fixed in next commit, uploading a test build right now.

EDIT: [here](https://drive.google.com/file/d/1EwdWtf30-kDKFDggJ3OTzlrSvai27Uhk/view?usp=sharing) it is !
