### ISSUE TITLE
Totally random thoughts after spending a full evening using exp pipes.

### ISSUE THREAD

**Issue by BrewingCoder** [Firew0lf/exppipes#3]
Feel free to just close this out of hand, let me know if you want any of these items opened into separate issues, or if you're open to pull requests:

1. what I found most troublesome when attempting to create a pipe network was the lack of polymorphic-sink.  The provider pipe only provides 9 filter locations for sink items.  This makes the pipe useless on simple storage multi-block networks like Storage Drawers, Yabba, etc.
* [x] Done

*this also applies to mass sink machines like say ore crushing/washing where you want to sink a large number of items.  This used to be slapping on a LP MK-V Chassis with many sink modules in it.  Unfortunately a poly-sink wouldn't solve that issue.  In my test world I made multiple chests with many sinks, then a separate network to extract all those into the machine, but it wasn't ideal.

2. Even with a polymorphic sink of some type a provider needs an option to leave at least 1, or one stack, of an item in it's connected inventory.  This prevents those connected storage devices from potentially unlocking it's storage slot for that item.
* [x] Done

3. I still have issues with routing.  Not as bad as before your last update (which was amazing, more on that in a moment).  The network routing appears great but it doesn't always pick the default route.  On my test system I only have one default route, which is a chest. It's purpose is to catch everything that doesn't have a specific route.  In places I have Yabba barrel networks and Storage drawer networks with provider pipes.  These pipes DO NOT have default route set, and have specific item sink entries.
 * [x] Fixed

If I put an empty barrel on the Yabba network, which is closer to the extraction point than the Storage Drawers network, the pipes will route something into the empty barrel.  It shouldn't do this right? the provider pipe doesn't have an entry for it.  There is a provider pipe about 10 blocks away on the Storage drawers network, but it ignored that in favor of the empty barrel.

4.  You totally conquered the issue I and others were having with large # of items in the network with your routing update.  Previously if I inserted mass amounts of items they would flail around inside the pipes back and forth before eventually finding a home.  I imagine that when you try to drop 20K items into a small network that poor routing was probably the issue.

5. Stack size, Stack size, Stack size. 1 per 4 ticks is slow.  Your network can handle it now, I know because I popped it up to extract full stacks at a time every 2 ticks, threw an RF tools builder at full speed piping crap into a chest, and it kept up with only two extractor pipes and very very very little routing issues.
 * [x] Done

Like I said. feel free to delete.  I just loved LP so much and am so disheartened at the speed at which they are working.  I get that personal time is sometimes hard but they do a commit once every two to three months.  by the time they clean it up we'll be on MC 1.15 and they'll bitch about all the work they have to do to upgrade :/

You are getting there so fast!

**Comment by BrewingCoder** [comment]
you can take a peek @ my fork for some other progress besides my pull-req. just a beginning. too tired and haven't fleshed out keeping the filter up to date yet.

**Comment by Ihamfp** [comment]
1. I looked at your code, if you manage to make something stable I will merge it here :p
2. I may add this as an upgrade... *adds it in the [list of ideas](https://github.com/Firew0lf/exppipes/projects/2)*
3. require investigation, if you could provide the map or a screenshot it would help a lot (my test setup for this is an array of chests with providers configured as sinks, one for each type of wool except the last two, and a routing pipe as default sink to another chest)
4. Actually the issue was complete stupidity... Some pipes would "connect" on the opposite side of where they should have, and items only continued flowing when the network gave up.
5. I planned upgrades for this (see list of ideas) to extract 16 and 64 items per extraction, will probably be there quickly (but I may use your code in the meantime if you open a pull request...).

Also the development will be hugely slowed down in the next 2-3 weeks, sorry for this... I'll try to fix/add as much as possible before this.

EDIT: I edited your comment to help tracking what's fixed

**Comment by BrewingCoder** [comment]
#3 is a UI Issue.. See here once it's done processing:  https://www.youtube.com/watch?v=_-2nnpjxOC8&feature=youtu.be

**Comment by Ihamfp** [comment]
The issue at 2:30 is fixed as of 0.2.0, as the config GUI now uses ghost slots (and doesn't handle the shift-click, could add it later tho, it's a minor feature).

**Comment by BrewingCoder** [comment]
I just merged your 0.2.0 code into my world.  it cleared the sink config on the normal provider pipes.  as soon as I destroyed one of those pipes to re-add it the world crashed.  I'm heading off to work but wanted you to see this before you potentially published it:
[07:17:08] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking block entity
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:848) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:743) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:192) ~[IntegratedServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:592) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: java.lang.NullPointerException
	at ihamfp.exppipes.pipenetwork.BlockDimPos.<init>(BlockDimPos.java:21) ~[BlockDimPos.class:?]
	at ihamfp.exppipes.tileentities.TileEntityRoutingPipe.serverUpdate(TileEntityRoutingPipe.java:211) ~[TileEntityRoutingPipe.class:?]
	at ihamfp.exppipes.tileentities.TileEntityPipe.update(TileEntityPipe.java:35) ~[TileEntityPipe.class:?]
	at net.minecraft.world.World.updateEntities(World.java:2019) ~[World.class:?]
	at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:643) ~[WorldServer.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:842) ~[MinecraftServer.class:?]
	... 4 more
[07:17:08] [Server thread/ERROR] [minecraft/MinecraftServer]: This crash report has been saved to: D:\Code\exppipes\run\.\crash-reports\crash-2019-04-26_07.17.08-server.txt

**Comment by Ihamfp** [comment]
Marked 3. as fixed as the UI is fixed.
