### ISSUE TITLE
FR:  ability to use wrench to enable/disable connection on one side of pipe

### ISSUE THREAD

**Issue by BrewingCoder** [Firew0lf/exppipes#6]
I know this is a biggie since it will totally mess with blockstates, textures, etc.  which are things that I totally hate about mods -- mostly because they confuse me.  But when running a pipe near an inventory there needs to be some way to prevent it from connecting on one side while maintaining a connection on the other.  (otherwise I'd use the non connecting pipe)

**Comment by Ihamfp** [comment]
Should be doable, but it would require rewriting the whole collision box thing... I'll take a look when I add multipart support.

**Comment by Ihamfp** [comment]
I added a feature to prevent connection but didn't test it well (not much time until at least next week), it doesn't use wrenches for now but I may add it to the config (like a list of items considered as wrenches), as exppipes itself doesn't have a wrench.
Also it shouldn't work with anything extracting items and routing pipes will behave... strangely. It's just for normal pipes.

(EDIT: obviously, how I detect the clicked side is more a hack than anything, but it kinda works)

**Comment by Ihamfp** [comment]
Still not using a wrench, but now working !
