### ISSUE TITLE
CurseForge Release

### ISSUE THREAD

**Issue by bziemons** [Firew0lf/exppipes#9]
From your readme
> Logistics Pipes is released under the MMPL license, which mostly covers the code, thus I don't really know if I can release this mod on Curseforge of something.

why not? Paragraph 6 of the MMPL 1.0.1 (as in our repository) tells you how you may distribute all or parts of MMPL licensed work.

**Comment by Ihamfp** [comment]
I [did](https://minecraft.curseforge.com/projects/exponentialistics-pipes) release it a while back, and was waiting for confirmation that I could indeed do it to remove the message from the readme. I joined your discord server around version 0.2.0's release date and never found a way to ask without self-promoting x).
Thanks for posting this this, I'm modifying the readme right now !

**Comment by bziemons** [comment]
You are welcome to write about your project in our Discord :) Really love to see this and I think others will love it, too
